language: node_js
cache:
  directories:
    - "node_modules"
node_js:
  - lts/*
branches:
  only: master
script:
  - mv readme.md alt.md
  - echo "---\nhome: true\nsidebar: true\n---" | cat - alt.md > readme.md
  - rm alt.md
  - npm run ci
