language: node_js
cache:
  directories:
    - "node_modules"
node_js:
  - lts/*
branches:
  only: master
script:
  - mv readme.md alt.md
  - SPACE=' '
  - echo -e "---\nhome:${SPACE}true\nsidebar:${SPACE}true\n---" > readme.md
  - cat alt.md >> readme.md
  - rm alt.md
  - npm run ci
